# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SETUP_SCRIPT
export DEBIAN_FRONTEND=noninteractive
add-apt-repository -y ppa:ondrej/apache2
add-apt-repository -y ppa:ondrej/php
apt-get -y update
apt-get -y install apache2 php7.0 libapache2-mod-php7.0 nghttp2-client
a2enmod http2
a2enmod ssl
a2enmod rewrite
mkdir -p /etc/apache2/cert/
openssl req -nodes -newkey rsa:2048 -keyout /etc/apache2/cert/http2.key -out /etc/apache2/cert/http2.csr -subj "/C=US/ST=Tennessee/L=Nashville/O=Acme Corporation/OU=Technology Department/CN=localhost"
openssl x509 -req -days 365 -in /etc/apache2/cert/http2.csr -signkey /etc/apache2/cert/http2.key -out /etc/apache2/cert/http2.crt
rm /etc/apache2/sites-enabled/000-default.conf
ln -s /vagrant/apache2/http2.conf /etc/apache2/conf-enabled/http2.conf
ln -s /vagrant/apache2/localhost.conf /etc/apache2/sites-enabled/localhost.conf
service apache2 restart
SETUP_SCRIPT

Vagrant.configure(2) do |config|

    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "http2-apache"
    config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    config.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: true
    config.vm.provision "shell", inline: $script
    config.vm.synced_folder "..", "/vagrant"

    config.vm.provider :virtualbox do |virtualbox|
        virtualbox.customize ["modifyvm", :id, "--name", "http2-apache"]

        # Uncomment the following lines in order to generate a pcap file for use
        # inspecting traffic to/from the VM with Wireshark
        #virtualbox.customize ["modifyvm", :id, "--nictrace1", "on"]
        #virtualbox.customize ["modifyvm", :id, "--nictracefile1", "trace1.pcap"]
    end

end